[package]
name = "c3dio"
version = "0.1.0"
edition = "2021"
exclude = ["tests", "tests/*", "examples", "examples/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"

[[bin]]
name = "c3dio"
path = "src/main.rs"

